version: '3'
services:
    cv_1_assign:
        runtime: nvidia
        user: $UID:$GID
        build:
            context: .
            args:
                UID: $UID
                GID: $GID
                UNAME: $UNAME
        volumes:
            - ./src:/src
            - ./res:/res
        # command: python /src/main.py ex_name=assignment1 model=convnet,resnet,lenet,fcn num_data=1000,60000 -m 
        command: python /src/main.py ex_name=assignment2 model=lenet num_data=1000 transforms.kwargs.affine=false,true transforms.kwargs.normalize=true,false transforms.kwargs.rotate=true,false -m
