ex_name: test

# for ConvNet
# net:
#         name: ConvNet
#         kwargs:
#             in_chan: 1
#             scale_factor: 1
#             num_layer: 5
#             kernel_size: 3
#             act_fn: ReLU
#             maxpool_freq: 2
#             bias: true
#             linear_in: 288
#             linear_num: 2
#             l_scale_factor: 0.5
#             out_chan: 10
#             base: 32
#             final: Softmax

# for resnet
# net:
#         name: ResNet
#         kwargs:
#                 in_chan: 1
#                 base: 64
#                 num_layer: 6
#                 kernel_size: 3
#                 act_fn: ReLU
#                 maxpool_freq: 3
#                 bias: true
#                 linear_in: 3136
#                 linear_num: 2
#                 scale_factor: 0.5
#                 out_chan: 10
#                 final: Softmax

defaults:
        - model: resnet

solver:
        kwargs:
                epochs: 300
                device: cuda
                save_dir: model

dataloader:
        kwargs:
            batch_size: 64
            shuffle: true
            num_workers: 6

optim:
        name: Adam
        kwargs:
                lr : 1e-5
                betas : [0.9,0.999]
                eps : 1e-8
                weight_decay : 0

scheduler:
        name: StepLR
        kwargs:
                step_size: 100
                gamma: 0.1
                last_epoch: -1

loss: CrossEntropyLoss

num_data: 60000
